#!/bin/bash
# Generate Gateway server list from GIIP database
# This script fetches server configurations including encrypted passwords
# and creates the giipAgentGateway_servers.csv file

# Load configuration (scripts 폴더에서 실행하므로 상위 폴더 참조)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -f "${SCRIPT_DIR}/../giipAgent.cnf" ]; then
    echo "Error: giipAgent.cnf not found"
    echo "Expected location: ${SCRIPT_DIR}/../giipAgent.cnf"
    exit 1
fi

. "${SCRIPT_DIR}/../giipAgent.cnf"

# Check required tools
if ! command -v sqlcmd &> /dev/null; then
    echo "Error: sqlcmd is not installed"
    echo "Install mssql-tools: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools"
    exit 1
fi

# Database connection parameters
DB_SERVER="${db_server:-localhost}"
DB_NAME="${db_name:-giipDB}"
DB_USER="${db_user}"
DB_PASS="${db_password}"

if [ -z "$DB_USER" ] || [ -z "$DB_PASS" ]; then
    echo "Error: Database credentials not configured in giipAgent.cnf"
    echo "Add: db_server, db_name, db_user, db_password"
    exit 1
fi

OUTPUT_FILE="./giipAgentGateway_servers.csv"
TEMP_FILE="/tmp/gateway_servers_$$.csv"

echo "Fetching server list from database..."

# SQL query to get remote servers with decrypted passwords
SQL_QUERY="
SET NOCOUNT ON;
SELECT 
    remote.LSHostname AS hostname,
    remote.LSsn AS lssn,
    remote.gateway_ssh_host AS ssh_host,
    ISNULL(remote.gateway_ssh_user, 'root') AS ssh_user,
    ISNULL(remote.gateway_ssh_port, 22) AS ssh_port,
    ISNULL(remote.gateway_ssh_key_path, '') AS ssh_key_path,
    ISNULL(dbo.lwDecryptPassword(remote.gateway_ssh_password), '') AS ssh_password,
    ISNULL(remote.LSOSVer, 'Linux') AS os_info,
    1 AS enabled
FROM tLSvr remote WITH(NOLOCK)
WHERE remote.gateway_lssn IS NOT NULL
  AND remote.is_gateway = 0
  AND remote.gateway_ssh_host IS NOT NULL
ORDER BY remote.LSHostname;
"

# Execute query and save to temp file
sqlcmd -S "$DB_SERVER" -d "$DB_NAME" -U "$DB_USER" -P "$DB_PASS" \
    -Q "$SQL_QUERY" -s "," -W -h -1 > "$TEMP_FILE" 2>&1

if [ $? -ne 0 ]; then
    echo "Error: Failed to query database"
    cat "$TEMP_FILE"
    rm -f "$TEMP_FILE"
    exit 1
fi

# Check if we got results
if [ ! -s "$TEMP_FILE" ]; then
    echo "Warning: No servers found in database"
    rm -f "$TEMP_FILE"
    exit 0
fi

# Create output file with header
cat > "$OUTPUT_FILE" << 'EOF'
# GIIP Agent Gateway - Server List (Auto-generated from database)
# ⚠️ Generated by: sync-gateway-servers.sh
# DO NOT EDIT MANUALLY - Changes will be overwritten!
# 
# To regenerate: ./sync-gateway-servers.sh
# Last generated: $(date '+%Y-%m-%d %H:%M:%S')
#
# CSV Format: hostname,lssn,ssh_host,ssh_user,ssh_port,ssh_key_path,ssh_password,os_info,enabled
#
# hostname,lssn,ssh_host,ssh_user,ssh_port,ssh_key_path,ssh_password,os_info,enabled
EOF

# Process the temp file (remove header and trailing spaces)
tail -n +2 "$TEMP_FILE" | sed 's/[[:space:]]*$//' | grep -v "^$" >> "$OUTPUT_FILE"

rm -f "$TEMP_FILE"

# Set restrictive permissions (contains passwords!)
chmod 600 "$OUTPUT_FILE"

# Count servers
SERVER_COUNT=$(grep -v "^#" "$OUTPUT_FILE" | grep -v "^$" | wc -l)

echo "✅ Server list generated successfully"
echo "   File: $OUTPUT_FILE"
echo "   Servers: $SERVER_COUNT"
echo "   Permissions: 600 (read/write owner only)"
echo ""
echo "⚠️  SECURITY WARNING:"
echo "   This file contains DECRYPTED passwords!"
echo "   - Keep file permissions strict (600)"
echo "   - Do not commit to git"
echo "   - Regenerate regularly to sync with database"
echo ""
echo "Next steps:"
echo "1. Install sshpass (if using password auth): sudo ../admin/install-sshpass.sh"
echo "2. Test connection: ssh user@host"
echo "3. Start gateway agent: ../gateway/giipAgentGateway.sh"
